### ISSUE TITLE
Data model

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#1]
Based on https://trello.com/c/wXa0dJqb/23-robert-to-build-wireframe-using-balsamiq these are the tables I think we'll need:

- `users` - I figure https://github.com/plataformatec/devise would be a good gem for authentication. I've used it before, it'll generate a `users` table for us with username, password, etc. We could also put fields like `discord_user_id` and the like on this table if we want.
- `maps`
    - `id`
    - `name` - e.g., Watchpoint Gibraltar
    - `type` - payload, escort, hybrid, control
    - ~`slug` - for use in the URL, e.g., watchpoint-gibraltar~
- `compositions` - this will have 1+ `player_selections` records
    - `id`
    - `name` - e.g., Rob's Fave Picks
    - `notes`
    - ~`slug` - for use in the URL, e.g., robs-fave-picks~
    - `map_id` - which map is this team composition for?
- `players`
    - `id`
    - `name` - e.g., Sarah
    - `battlenet` - e.g., jimbob#1234
    - `user_id` - is the player another user of the app?
- `heroes`
    - `id`
    - `name` - e.g., Hanzo
- `player_selections`
    - `id`
    - `player_id`
    - `hero_id`
    - `role` - e.g., support, offense payload 1, defense capture point
    - `composition_id` - a field to tie this player + hero combination back to a particular composition
- `hero_pools` - I'm open to a better name for this join table that hooks up players with the heroes they're comfortable playing
    - `player_id`
    - `hero_id`
    - `confidence` - ~thinking a floating point value between 0-1 that indicates how comfortable the player is with this hero, like 0.75 for fairly confident, 0.1 for not confident at all~ actually I'll probably make this an integer between 0-100 because floating point is scary

/cc @justbarreto @RobThePM

**Comment by RobThePM** [comment]
do we need one table that would be for each point of each map? for example: offense cp 1, offense cp 2, defense cp 1, defense cp 2, koth "oasis_university", koth "oasis_gardens", etc. i don't know the best way to design it.

**Comment by RobThePM** [comment]
nevermind, i see the role field now and i think that's what captures it, right?

**Comment by cheshire137** [comment]
That was the idea of the role field, but maybe it's not enough. I could see us having this table, too:

- `map_sections`
    - `id`
    - `map_id`
    - `name` - e.g., cap 1, payload 2

Then we'd have a `map_section_id` in `player_selections`. Having a separate table like this could let us more easily query things like "which heroes are most popular on point 2 Hanamura". What do you think?

> koth "oasis_university", koth "oasis_gardens"

I would treat these as two separate maps. So there'd be a separate `maps` record for Oasis University from Oasis Gardens. We could tie such maps together via additional tables if we wanted, but I don't think it's necessary yet.

**Comment by cheshire137** [comment]
An open question here is about players versus users. I have them as separate concepts because maybe the person building the team comp for his friends is the only user of the app in that group. He needs to be able to represent his friends as players in a composition. But maybe his friends are also users of the app and they want to specify their own hero pools and how confident they are on each hero. So the person building the team comp says "yeah this Sarah on my team, she's this particular user." I don't know if this setup is the best. Any thoughts on this @rewinfrey?

**Comment by ihavenotea** [comment]
Devise is a good choice if we are using rails. 

I do believe that having a concept of Player that is separate from User will be hugely beneficial. 

We should also look at the official blizzard API for pulling stats and try's and line up our names of things with theirs. 

We will likely want to be able to enable a "use my stats" type feature to build team comps based on past performance and if we already follow blizzards conventions for maps and characters, etc it will be simpler.

**Comment by cheshire137** [comment]
> We should also look at the official blizzard API for pulling stats and try's and line up our names of things with theirs.

Oh that's a good idea, that should help make things clear. Are you thinking of the values we'd use, like in a map type field saying "control" instead of "king of the hill", or are you also talking about some field/table names?

**Comment by cheshire137** [comment]
I think the `slug` columns can be dropped if we use the [friendly_id gem](https://github.com/norman/friendly_id) since it looks like it stores slugs in a central table.

**Comment by cheshire137** [comment]
The "Offense Payload 1", etc. labels in the mockup in https://trello.com/c/wXa0dJqb/23-mockups-version-1 should probably also be stored in the database. Maybe:

- `map_segments`
    - `id`
    - `map_id` - reference to the map this applies to
    - `name` - e.g., Offense Payload 1

A map could have 0+ map segments. Can you think about the sections of each Overwatch map @RobThePM where you would like to specify a different team composition? E.g. player A goes Lúcio on point A but switches to Mercy for point B.

**Comment by cheshire137** [comment]
I landed #5 so I'll close this out. We can make further modifications as necessary to the data model via Rails migrations! 🎉

**Comment by RobThePM** [comment]
sorry, i saw this one late as well. i might be getting email notifications late or something, i'll keep an eye out to see if it's an issue with my email or if it's my human error.

> Can you think about the sections of each Overwatch map @RobThePM where you would like to specify a different team composition? E.g. player A goes Lúcio on point A but switches to Mercy for point B.

sorry chesh, i don't quite understand what you're asking me here. i think you're asking me how we decide how many team comps we have per map (e.g. columns). if that's what you're asking me, then the answer is the number of checkpoints on the map, both sides included where applicable. it follows the same schema as my google sheet: https://docs.google.com/spreadsheets/d/1zstpx2-vZfGX9sgfHy5vtOmJUFOaYowtlp3l1xWbhE8/edit#gid=823800667.

for example, on King's Row there would be a total of 6 columns to populate team compositions. 3 of them are on attack: the first control point, the first payload checkpoint, and then the final payload checkpoint. then you add another 3 for playing on defense.

for king of the hill maps, there would only be 3 team compositions since there are only 3 'sub-maps' on koth maps and there's no such thing as 'the team on attack' and 'the team on defense'.

i'm not sure if this answers your question. does it?

**Comment by cheshire137** [comment]
It does! And I also forgot about that spreadsheet somehow! The list of sections I was wanting in your language is right there in the spreadsheet. 😀 Also, I think for the control maps, I'll change how I was going to store them as separate maps and instead do what you're saying and what Stephanie's mockup showed: just separate sections for the same map.
