### ISSUE TITLE
"Sign in with Battle.net" label still shows after signing in

### ISSUE THREAD

**Issue by RobThePM** [cheshire137/overwatch-team-comps#104]
1. I was on the team comp page shown below.
2. I was not logged in (I think).
3. I put in some random names and heroes.
4. Then I clicked on the "Sign in with Battle.net" link in the upper right. The screen went white for a second, then it loaded my previously saved heroes (different heroes than what I entered in step #3, above). I never went to a sign in page as I think it remembered my login from last time.
5. At this point I assume I am logged in, but the link in the upper right hand corner still says "Sign in with Battle.net".

![image](https://cloud.githubusercontent.com/assets/26153402/24326244/93fa700e-1167-11e7-9cf7-f5d2b13a7a49.png)

**Comment by cheshire137** [comment]
Hmm, I wonder if you were signed in in a different browser profile. Can you open the Chrome inspector via Ctrl-Shift-I and go to the "Application" tab. On the left side, expand "Local Storage" and click the "https://overwatch-team..." item under it. In the right pane, do you have an `overwatch-team-comps` key with a value that has your battletag in it?

Also in the Chrome inspector under "Application," expand "Cookies" and click the "https://overwatch-team..." item under it. In the right pane, do you have a line with "_overwatch-team-comps_session" as the name?

**Comment by cheshire137** [comment]
Oh cool, I was able to reproduce this! The local storage has battletag: null in it. I must have had my local storage value set from a previous time I logged in. I'll get this fixed!

**Comment by cheshire137** [comment]
This should be fixed now, Rob. Try it again and let me know!

**Comment by RobThePM** [comment]
I'm seeing that I'm signed in, but now I can't sign out, I'm trapped in here! 😄 

![image](https://cloud.githubusercontent.com/assets/26153402/24326924/6ed8737e-1177-11e7-9341-cf568857979a.png)

**Comment by cheshire137** [comment]
This app is basically Hotel California. 😀 We haven't added a sign out link yet.

**Comment by RobThePM** [comment]
Got it, thanks!
