### ISSUE TITLE
Question: When users share their team comp, do the URL's need to be unique (and will they persist)?

### ISSUE THREAD

**Issue by RobThePM** [cheshire137/overwatch-team-comps#132]
**Can two different users generate the same URL address when they share their team comp?**
I'm looking at the URL when I click the 'Share this composition' link and I wonder if the URL needs to be more unique. Maybe combing user name (or Battletag), time stamp, composition name, etc. I think it would be good to have unique URL's if possible. However, if it takes too much development time I would be okay with pushing it to a future version.

**On a related note, do the URL's persist forever?**
For example, if someone posts the URL in a forum, will that URL continue to link back to the page with the saved team comp forever? I think it would be good to have that, too, but if it takes too long we can push to a future version.

_Note that these questions are related to our requirement RQ04:_
_As an end user, I want to be able to somehow easily share my saved team comps and hero
pools with other users (e.g. copy the link, send it to my friend, they click on the link and it
automatically takes them to the specific page with my saved team composition)._

**Comment by RobThePM** [comment]
I don't know if this is related to #52.

**Comment by cheshire137** [comment]
> On a related note, do the URL's persist forever?

Yep, that's how it works currently. The only reason a URL would stop working is if we wiped that composition from the database. We're using Heroku for hosting the app and it has [limits to its free database use](https://devcenter.heroku.com/articles/heroku-postgres-plans#hobby-tier), however I think we don't need to worry about that for a while.

**Comment by RobThePM** [comment]
> Nope, the URL is made different even if you create two compositions with the same name for the same map.
> 
> We're using the friendly ID gem to generate these URLs.

Nice! This is exactly how it should function!

> Yep, that's how it works currently.

Excellent! This, too, is how it should function!
