### ISSUE TITLE
Let a team organizer create players

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#16]
See this mockup: https://trello.com/c/wXa0dJqb/23-mockups-version-1

As I type the names of the players in my group, those should be persisted as Player records by hitting an endpoint via AJAX request. So if I'm Rob, I can put Cheshire and Zion on my team.

**Comment by cheshire137** [comment]
It would be nice to prepopulate the player name fields for a team organizer after they've already saved one team comp. So when Rob goes to organize another map for his group, we fill out Cheshire, Zion, Siege, etc. because those were the last players he used in a previous comp.

We can get this list of previously used players for a given user by looking at the user's most recently created Composition record. From that Composition, we find all the PlayerSelections, then we get the Player records off those.

We could possibly make this connection more explicit by adding a `creator_id` field to the `players` table. So if Rob puts Cheshire in a comp, the `players` table might have `user_id` pointing at Cheshire's user if she ever signs into the app herself, and `creator_id` pointing at Rob.

**Comment by rewinfrey** [comment]
> We can get this list of previously used players for a given user by looking at the user's most recently created Composition record. From that Composition, we find all the PlayerSelections, then we get the Player records off those.

@cheshire137 👍 since we talked about this in tonight's games, I just saw this note and think this is great, especially for v1.

**Comment by cheshire137** [comment]
This was done with #57, #61, #79.
