### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#17]
I figured we'd use Travis CI for this. I may have to toggle some switch on Travis since the repo is tied to my GitHub user. We need a Travis config file in the repo, though, before I toggle said switch. Ideally, Travis would run Rails tests via `RAILS_ENV=test rake test` for us. So Travis will also have to run database migrations via `RAILS_ENV=test bin/rake db:migrate` before it runs tests. Once we add some style checkers like ESLint and Rubocop -- see #8 -- Travis should also incorporate those. 

#13 adds our first tests, so this issue would make sense to complete after that lands.

We'll probably want the following cache options for Travis:

```yaml
cache:
  directories:
  - vendor/bundle
  - node_modules
```

/cc @pseudobeard ❤️

**Comment by rewinfrey** [comment]
If #26 lands, we'd want to update the invocation of the test run with:

`RAILS_ENV=test bundle exec spec`

**Comment by cheshire137** [comment]
JS style checking has landed, so `npm run style` can be part of this.

**Comment by cheshire137** [comment]
JS unit tests have landed, so `npm run unit-test` can be part of this.
