### ISSUE TITLE
Create a Slack team

### ISSUE THREAD

**Issue by rewinfrey** [cheshire137/overwatch-team-comps#24]
I'd like to propose Slack as a fun way to communicate and share in the camaraderie of working on this project. The use of Slack is not to take the place of Trello cards or GitHub, but it often can serve as useful place to bounce ideas off the group and get feedback. It's also a fun way to build communities!

Is there any interest in creating a Slack team for this project?

/cc @RobThePM @cheshire137

**Comment by RobThePM** [comment]
I took a quick look at Slack. I might be interested in using this, but my initial thoughts are let's complete Version 1 first using GitHub and Trello, then if we work on Version 2 we can decide how we might use Slack. Just my 2 cents - but Slack does seem like it would have some great, fun advantages!

**Comment by rewinfrey** [comment]
> if we work on Version 2 we can decide how we might use Slack

@RobThePM sounds good! I will close this out for now. If we determine there is a need later on, we can explore this then 😄

**Comment by cheshire137** [comment]
Rather than a Slack team, we could make use of [Gitter](https://gitter.im/) which I think lets you have a chat channel based on a repository.

**Comment by RobThePM** [comment]
I'm down if that's something you guys want. :)
