### ISSUE TITLE
Add "Clear Sans" Typeface

### ISSUE THREAD

**Issue by smbriones** [cheshire137/overwatch-team-comps#27]
This is the typeface I've been using in the design so far. Can we add the webfont to our project to start adding font styles? I'm mostly using Regular, Medium, and Bold, but it would be nice to have all of the weights.

I think this makes it simple, but also happy to add them via font-face:
https://github.com/resir014/Clear-Sans-Webfont

**Comment by cheshire137** [comment]
Oh nice, I wondered which font you had in your mockups!

**Comment by cheshire137** [comment]
I'll pull this into #10.

**Comment by smbriones** [comment]
@cheshire137 yay! thank you!

**Comment by cheshire137** [comment]
Lol, maybe I'll link to the CDN version of the font...

<img width="1088" alt="start_on_team_composition_form_by_cheshire137_ _pull_request__10_ _cheshire137_overwatch-team-comps" src="https://cloud.githubusercontent.com/assets/82317/23594330/d60ccf70-01de-11e7-90b6-ea46a749fee5.png">
