### ISSUE TITLE
Add a couple new database fields

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#30]
Based on our call yesterday, we need the following adjustments to our data model, made via Rails migrations:

- ~Add nullable string `battlenet` field to `users` table, to mirror the same field already in the `players` table~ -- this will be handled as part of #33
- Add nullable text `video_url` field to `compositions` table
- Add non-nullable string `session_id` field to `compositions` table. We can probably put a limit of 32 on it, based on http://guides.rubyonrails.org/security.html.
- Modify `compositions.user_id` to be non-nullable.

@rewinfrey does this seem right to you?

**Comment by rewinfrey** [comment]
@cheshire137 👍 this covers the requirements!

For `video_url`, I wonder if we would want to add `video_name` and `video_description` columns for the video resource? Or is there another way you were thinking we could enable a team manager to explain why the video is shared on the team comp page?

--------------

I had a couple other thoughts about the data model here that are non-critical and do not need to impact v1. I think the points below are very easy to change or transition to if the project needs them, but I think it would be premature to change the data model now. Mostly I think these are fun ideas to consider, and note them here in case they may be helpful in the future. **These are not suggestions for now** 😄 

`battlenet`

This ties us to Blizzard, but there was some conversation about this app being used in other game contexts besides Overwatch. Later on we might consider naming this field generically as `gamertag` and use this to store what represents a player's battletag, steam id, psn, or other gamer platform user name. However, the gotcha is a player could have multiple gamertags which most likely hints at an association. Players can have many gamertags. That then introduces a new table, join relation, etc. Or we add additional columns for each game platform: `steam`, `psn`, etc.

`video_url`

This seems to indicate that over time, we'd want to enable a team manager to load multiple videos for a team composition, in which case we'd likely want a join relation here with a `video_resources` table. Like I mention above `name` and `description` columns, it might be helpful for providing context for a video resource.
