### ISSUE TITLE
Support Markdown formatting in the 'notes' text field

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#32]
There are a few parts to supporting Markdown in the 'notes' field:

- When we render the notes on a static page where the user can't edit them, we should convert the Markdown to HTML so that links, boldface, and other formatting appears.
- In the composition edit form, it would be cool to offer a toolbar so the user doesn't have to manually type Markdown if they don't want to. This isn't critical, but maybe there's a simple drop-in solution?
    <img width="407" alt="new_issue_ _cheshire137_overwatch-team-comps" src="https://cloud.githubusercontent.com/assets/82317/23618963/c007a2b2-0257-11e7-84b7-bb07ab372f06.png">
- We should strip certain kinds of formatting from the 'notes' field, either on render or before we save the value in the database. `style` attributes, `img` tags, `embed` tags, etc. we don't want to render.

**Comment by rewinfrey** [comment]
I haven't looked at the code, but this looks like a possible solution:

https://simplemde.com

I'll plug this in and give it a try. The thing that makes this appealing is it offers hooks apparently for auto-save.

**Comment by cheshire137** [comment]
> it offers hooks apparently for auto-save.

That sounds great! Otherwise we'd be doing our own debounce as the user types or an onBlur handler to save the notes.
