### ISSUE TITLE
Load previously saved composition on page load

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#53]
When I load the app again after having saved a composition before, the player names, hero selections, map, composition notes, and composition name should be populated with the values from that previous composition of mine.

It would be nice if the front end just had to make one request to get composition details regardless of whether it's a new composition or a previously saved one. Maybe an /api/compositions/load endpoint would be better than the /api/compositions/new request that the front end makes now? This would parallel the existing /api/compositions/save endpoint.

- Add a new /api/compositions/load endpoint that determines, based on the `current_user` or the `session.id` if `current_user` is nil, what the last modified Composition is, if any, for that user/session. It should respond with the same JSON structure as in new.json.
- Remove the /api/compositions/new endpoint. Reuse its tests for the /api/compositions/load endpoint.
- Change the front end to hit /api/compositions/load instead of /api/compositions/new. This will mean a different method in OverwatchTeamCompsApi and a different call in CompositionForm.

**Comment by rewinfrey** [comment]
@cheshire137 curious why not use REST conventions here and have a `new`, `show`, `create`, etc endpoints?

Something that I think would help here possibly is an `index` route, so a user can see their existing comps. Initial thought is we could group previously saved comps by map, and have a way to grouping those together in an index view. Otherwise, just one large list of all previously saved comps is going to be a pain to search through.

**Comment by cheshire137** [comment]
> why not use REST conventions here and have a new, show, create, etc endpoints?

I don't think we need all of those. 'new' and 'show' especially seem like they don't make sense in an API where you just have back-end endpoints. I think we'll need to fetch existing compositions, fetch a list of existing compositions, and save a composition. I could see splitting create and update for saving a composition, and if that's easier to implement we can do so. As the /save endpoint is now, it can handle both creating and updating existing records.

We could split up the compositions#save endpoint into separate endpoints in different controllers if you want. So a user chooses a hero from a select menu, we hit an endpoint in a PlayerSelections. It will need to know enough about the composition, though, to be able to create/update the necessary join records.

> I think would help here possibly is an index route

I agree! I think that'll be a separate Issue, though, when we're ready to let the user switch between their saved compositions. We'll need an endpoint for fetching the current user/session's saved compositions, and then the React front end to make use of that list.
