### ISSUE TITLE
Fill out all map segments when first hero is selected for a player

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#68]
If @RobThePM starts on Sombra, he's probably gonna stay on Sombra. 😀  Facilitate this for the team organizer by selecting the same hero for each map segment when the first selection is made for a player.

**Comment by RobThePM** [comment]
nice quality of life idea! (did i use the term "quality of life" correctly in relation to this feature?)

**Comment by RobThePM** [comment]
Question...

Zion is making his team comp for Hanamura. He picks Genji as his hero on Defense Point 1 (assuming that defense point 1 is the first column on the left). It auto fills Genji for the rest of the hero slots in that row. Then he picks Sombra for Defense Point 2. Then he picks Mercy for Defense Point 1. What will the hero selections look like for that row?

I'm wondering if it will change all selections for that row to Mercy.

**Comment by cheshire137** [comment]
Nope, it only auto populates the unselected slots.

**Comment by RobThePM** [comment]
I'm actually using this right now and it's an awesome feature. Thanks for implementing. Saves me so much time.
