### ISSUE TITLE
Get map images for the header

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#74]
In @smbriones' mockup, she used a pretty photo of the map in the header area:

![Map](https://raw.githubusercontent.com/cheshire137/overwatch-team-comps/master/mockups/readme%20screens%20-%20team%20comp%20form%2001.png)

We need such an image for each map in the game. My thinking is we can get these images ourselves from inside Overwatch by taking a screenshot. Ideally we'd use the highest resolution possible so we have more options for cropping the image while keeping the quality high.

I have a 2560x1440 resolution; does anyone have higher? Maybe we don't even need that high. Go sightseeing in the game, find a pretty view of the map, grab a screenshot. 📸 Perhaps you can use the spectator camera controls to get to a good viewpoint?

**Comment by cheshire137** [comment]
Share the images you get here, @RobThePM! The one you mentioned in #81.

**Comment by RobThePM** [comment]
my new ETA for this will be end of week - i'm still a little sick :(

**Comment by cheshire137** [comment]
No worries, Rob! No pressure on the timing, I just pinged you over here since I closed #81 out. Feel better! 🤒

**Comment by RobThePM** [comment]
@cheshire137 @smbriones 

Here's some screenshots for Hanamura for now. I thought I would take a few so that you had some options and also just in case you wanted to use multiple screenshots, etc. I can crop out the HUD at the top going forward if you'd like, too.

Fun fact... there's a delay when using the free roam camera in spectator mode and it's a little clunky in general; as a result it gave me motion sickness, which is why I didn't finish. Hopefully these will do for now! 😄 

![hanamura 01](https://cloud.githubusercontent.com/assets/26153402/24327441/5c77e43a-1186-11e7-9b0a-7e500b1f6279.png)
![hanamura 02](https://cloud.githubusercontent.com/assets/26153402/24327440/5c777004-1186-11e7-9923-434ced727297.png)
![hanamura 03](https://cloud.githubusercontent.com/assets/26153402/24327444/5c7995e6-1186-11e7-90a9-aadc18e051b4.png)
![hanamura 04](https://cloud.githubusercontent.com/assets/26153402/24327443/5c795e3c-1186-11e7-8a7c-0eab1c20892c.png)
![hanamura 05](https://cloud.githubusercontent.com/assets/26153402/24327442/5c79347a-1186-11e7-9914-678f9a54e8da.png)
![hanamura 06](https://cloud.githubusercontent.com/assets/26153402/24327445/5c79d70e-1186-11e7-921a-e168561df4c3.png)
![hanamura 07](https://cloud.githubusercontent.com/assets/26153402/24327447/5c885d92-1186-11e7-83b9-cf6b10ec8fad.png)
![hanamura 50](https://cloud.githubusercontent.com/assets/26153402/24327446/5c8811e8-1186-11e7-8a76-9c7cba02f442.png)

**Comment by cheshire137** [comment]
> it gave me motion sickness

I appreciate your sacrifice, Rob! ❤ Thanks for these! They look nice coming from the free camera, since they're higher up and you can see a lot more of the map. Love the cherry blossoms!

**Comment by RobThePM** [comment]
A couple more for Hanamura. I wanted to get one of the front of the temple with the cherry blossoms.

![hanamura 08](https://cloud.githubusercontent.com/assets/26153402/24590352/7393324e-17a0-11e7-96f7-7218854880f7.png)

![hanamura 09](https://cloud.githubusercontent.com/assets/26153402/24590385/bd85d38e-17a0-11e7-9ef8-3dc53d85bf57.png)

**Comment by RobThePM** [comment]
Okay here's a few for Anubis. It's tough to get good shots of open areas because there's so many pillars and other obstacles in the way. I'm happy to take more pictures if needed.

![anubis 01](https://cloud.githubusercontent.com/assets/26153402/24590439/c26a833a-17a1-11e7-920a-375b567e5a3a.png)

![anubis 02](https://cloud.githubusercontent.com/assets/26153402/24590441/c26c3a72-17a1-11e7-898e-a40840af1aef.png)

![anubis 03](https://cloud.githubusercontent.com/assets/26153402/24590440/c26a9faa-17a1-11e7-9fed-42b68e2aa6da.png)

![anubis 04](https://cloud.githubusercontent.com/assets/26153402/24590442/c27d50d2-17a1-11e7-82f1-3210564fe9b8.png)

![anubis 05](https://cloud.githubusercontent.com/assets/26153402/24590438/c269c17a-17a1-11e7-95f9-d645059c6f0d.png)

**Comment by RobThePM** [comment]
And Volskya. That's it for now. I'll do more throughout the week!

![volskya 01](https://cloud.githubusercontent.com/assets/26153402/24590494/0d249ff4-17a3-11e7-9f6b-d6fee08612bd.png)

![volskya 02](https://cloud.githubusercontent.com/assets/26153402/24590499/0ee2e3a0-17a3-11e7-8a10-ff375ac3fe92.png)

![volskya 03](https://cloud.githubusercontent.com/assets/26153402/24590501/11096c3a-17a3-11e7-8efd-1a4912c222b7.png)

![volskya 04](https://cloud.githubusercontent.com/assets/26153402/24590506/19a8f39c-17a3-11e7-82d7-83fbb52069f0.png)

![volskya 05](https://cloud.githubusercontent.com/assets/26153402/24590509/19b92f28-17a3-11e7-9f44-222c9a2b7fe1.png)

![volskya 06](https://cloud.githubusercontent.com/assets/26153402/24590510/19ba15a0-17a3-11e7-862f-2210f6cca06f.png)

![volskya 07](https://cloud.githubusercontent.com/assets/26153402/24590511/19bbe542-17a3-11e7-975a-eeb13fc6b2a3.png)

![volskya 08](https://cloud.githubusercontent.com/assets/26153402/24590512/19be069c-17a3-11e7-8cf8-2828065ee355.png)

![volskya 09](https://cloud.githubusercontent.com/assets/26153402/24590503/19a6397c-17a3-11e7-9ab2-dae599a86a6f.png)

![volskya 10](https://cloud.githubusercontent.com/assets/26153402/24590504/19a7e34e-17a3-11e7-9146-137ce92b38db.png)

![volskya 11](https://cloud.githubusercontent.com/assets/26153402/24590505/19a8eb7c-17a3-11e7-9929-e316f2df99cf.png)

![volskya 12](https://cloud.githubusercontent.com/assets/26153402/24590507/19a987c6-17a3-11e7-9384-55c525b78cc5.png)

![volskya 13](https://cloud.githubusercontent.com/assets/26153402/24590508/19aa741a-17a3-11e7-8947-3b244b02d011.png)

**Comment by cheshire137** [comment]
Thanks Rob! I'll start snipping these and getting them in the app. 💛

**Comment by RobThePM** [comment]
I took some quick and dirty pictures of more maps. We can replace pictures with better ones later if needed. There's three more maps that I'll provide later.

Eichenwalde

![01](https://cloud.githubusercontent.com/assets/26153402/26568289/0a4e5748-44b7-11e7-9779-10834aa9b9b1.png)
![02](https://cloud.githubusercontent.com/assets/26153402/26568292/0d5985fc-44b7-11e7-8a77-db418864b243.png)
![03](https://cloud.githubusercontent.com/assets/26153402/26568293/0ed00262-44b7-11e7-8147-9ece74ed6714.png)

Hollywood

![01](https://cloud.githubusercontent.com/assets/26153402/26568296/16b3595c-44b7-11e7-8561-e807dbd0f8d1.png)
![02](https://cloud.githubusercontent.com/assets/26153402/26568298/19ab6f32-44b7-11e7-9e77-ec241fa030ca.png)

Ilios

![01](https://cloud.githubusercontent.com/assets/26153402/26568301/20349e0a-44b7-11e7-9845-28e23a75b6a8.png)
![02](https://cloud.githubusercontent.com/assets/26153402/26568303/2186655e-44b7-11e7-949d-b69e0a5d93f9.png)
![03](https://cloud.githubusercontent.com/assets/26153402/26568304/22bb0d62-44b7-11e7-8773-730f347a4f7a.png)

King's Row

![01](https://cloud.githubusercontent.com/assets/26153402/26568307/29c5f694-44b7-11e7-8388-9570e3fa206d.png)
![02](https://cloud.githubusercontent.com/assets/26153402/26568309/2b4657ca-44b7-11e7-81a4-1d6e12cf11a7.png)

Lijiang Tower

![01](https://cloud.githubusercontent.com/assets/26153402/26568311/3460c0b6-44b7-11e7-84cf-789c351bad20.png)
![02](https://cloud.githubusercontent.com/assets/26153402/26568313/357ae2e2-44b7-11e7-9d28-6b6f0907ae38.png)
![03](https://cloud.githubusercontent.com/assets/26153402/26568315/36b7ce40-44b7-11e7-9d66-3ee52105b113.png)

Nepal

![01](https://cloud.githubusercontent.com/assets/26153402/26568318/3d8b38ce-44b7-11e7-975f-68a4108040e3.png)
![02](https://cloud.githubusercontent.com/assets/26153402/26568319/3e904f98-44b7-11e7-9784-7b70657ca957.png)
![03](https://cloud.githubusercontent.com/assets/26153402/26568321/3f937ffa-44b7-11e7-87af-456f85da553f.png)

Numbani

![01](https://cloud.githubusercontent.com/assets/26153402/26568325/46c48c92-44b7-11e7-9f72-b735aeaa27d8.png)
![02](https://cloud.githubusercontent.com/assets/26153402/26568326/47ebb4d8-44b7-11e7-8b7d-52999c27e41f.png)
![03](https://cloud.githubusercontent.com/assets/26153402/26568327/49451680-44b7-11e7-8f5a-2647240ba93f.png)
![04](https://cloud.githubusercontent.com/assets/26153402/26568328/4a86e122-44b7-11e7-842f-8ed52e0c1657.png)
![05](https://cloud.githubusercontent.com/assets/26153402/26568329/4b98173e-44b7-11e7-8421-980a26529d96.png)

Oasis

![01](https://cloud.githubusercontent.com/assets/26153402/26568331/51eff822-44b7-11e7-864b-4fb415a023ee.png)
![02](https://cloud.githubusercontent.com/assets/26153402/26568332/52e4fd22-44b7-11e7-92cc-b504aefc5449.png)
![03](https://cloud.githubusercontent.com/assets/26153402/26568333/53e82d20-44b7-11e7-99e4-ff4765fbc659.png)
![04](https://cloud.githubusercontent.com/assets/26153402/26568334/54d8f890-44b7-11e7-8c3b-74d142846c81.png)

**Comment by RobThePM** [comment]
Dorado

![01](https://cloud.githubusercontent.com/assets/26153402/26619435/51639d64-4593-11e7-9c46-c79f7e170cb0.png)
![02](https://cloud.githubusercontent.com/assets/26153402/26619437/52d69c0a-4593-11e7-8042-b35f49f820e5.png)
![03](https://cloud.githubusercontent.com/assets/26153402/26619439/5452c806-4593-11e7-9b39-b1e23b4c923e.png)
![04](https://cloud.githubusercontent.com/assets/26153402/26619441/56120ff8-4593-11e7-90f8-4ae2e150b0c9.png)
![05](https://cloud.githubusercontent.com/assets/26153402/26619442/5789150c-4593-11e7-90e0-4cd47ee4fa06.png)
![06](https://cloud.githubusercontent.com/assets/26153402/26619444/58e5551e-4593-11e7-9d5b-7cc929220869.png)

**Comment by RobThePM** [comment]
Route 66

![05](https://user-images.githubusercontent.com/26153402/27004168-a5ad8a64-4db9-11e7-9edc-b60f7fb002e8.png)
![01](https://user-images.githubusercontent.com/26153402/27004169-a5b88a90-4db9-11e7-97d1-13607a2c6ce3.png)
![02](https://user-images.githubusercontent.com/26153402/27004171-a5bb4f46-4db9-11e7-81da-b8f820d85f17.png)
![03](https://user-images.githubusercontent.com/26153402/27004172-a5bcb66a-4db9-11e7-920d-779d9e89f6f2.png)
![04](https://user-images.githubusercontent.com/26153402/27004170-a5baa19a-4db9-11e7-8a59-619c0dc288d1.png)

and WPG

![08](https://user-images.githubusercontent.com/26153402/27004176-b56d1dac-4db9-11e7-8e97-32f013fc1683.png)
![01](https://user-images.githubusercontent.com/26153402/27004177-b579fd7e-4db9-11e7-9822-781b78bcda56.png)
![02](https://user-images.githubusercontent.com/26153402/27004181-b57c14e2-4db9-11e7-9b5c-29a26988495b.png)
![03](https://user-images.githubusercontent.com/26153402/27004179-b57b43c8-4db9-11e7-9f7b-240585a24871.png)
![04](https://user-images.githubusercontent.com/26153402/27004180-b57be666-4db9-11e7-8a47-eb4cb13198fd.png)
![05](https://user-images.githubusercontent.com/26153402/27004178-b57aaee0-4db9-11e7-99ce-813d2566f70a.png)
![06](https://user-images.githubusercontent.com/26153402/27004182-b580d626-4db9-11e7-8d2d-eb5512c57b63.png)
![07](https://user-images.githubusercontent.com/26153402/27004183-b58d5db0-4db9-11e7-94f9-6118f58a41f9.png)

**Comment by cheshire137** [comment]
Thanks for getting these, Rob! I've added them and all the maps have images now. 😎  Try flipping through the maps on https://overwatch-team-comps.herokuapp.com/.

**Comment by RobThePM** [comment]
I checked them all, looks great! Especially some of them like Dorado and Hollywood. Thanks!
