### ISSUE TITLE
Change composition form header color based on map

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#81]
The gradient used in the header of the composition form should change based on the map that's selected.

_Route 66 just isn't a pink-and-blue kind of map:_

<img width="1091" alt="overwatchteamcomps" src="https://cloud.githubusercontent.com/assets/82317/24067641/a5cb34dc-0b4d-11e7-97d9-d16d3121d08c.png">

@smbriones and @justbarreto, can you guys pick out some pretty colors and one of the devs can plug them in so that they change when the map selection changes?

This is related to #74.

**Comment by smbriones** [comment]
Hey, @cheshire137! Some of these could potentially be reused so we don't have 14 different gradients, but I went ahead and made one for each specific map. 🌈

What's the best way to share the color values?

![gradients](https://cloud.githubusercontent.com/assets/464760/24074805/f6448d8a-0bcc-11e7-89d2-d487d1a09b8f.png)

**Comment by cheshire137** [comment]
> What's the best way to share the color values?

I think probably I should print out your image, take a photo of it on my phone, print the photo, scan that, open it in MS Paint, zoom in real close, and use the eyedropper to select values. To keep things high fidelity, of course. 😀 

J/k, you could just list them out here as hex values!

**Comment by cheshire137** [comment]
The gradients are so pretty! Are the map images you used big enough to count for #74?

**Comment by smbriones** [comment]
🤣 Ok, sounds good!

> Are the map images you used big enough to count for #74?

They should be! I scaled them down for the sake of the mockups, but I'm not too sure it's actually legal to use the ones I found. 🤔 I thought your idea to take screenshots in #74 is our safest option because we'd be gathering them on our own.

Maybe @RobThePM or @rewinfrey have some thoughts there?

**Comment by smbriones** [comment]
@cheshire137 Here are the hex values!

### Assault Maps

**Hanamura**
#F3D7DA / #DAF0F8

**Temple of Anubis**
#FCEFE2 / #E8E9F8

**Volskaya Industries**
#E9F0FC / #F4E1F2

### Hybrid Maps

**Eichenwalde**
#E2F5FF / #E5EDDD

**Hollywood**
#FDF3E1 / #DAF0F8

**King’s Row**
#D6F1F3 / #FDFAEE

**Numbani**
#EDEFD8 / #ECEBFA


### Escort Maps

**Dorado**
#DCDCF4 / #DEF3F9

**Route 66**
#D6E2F3 / #FDEEE0

**Watchpoint: Gibraltar**
#ECE0F6 / #F8EEDA


### Control Maps

**Illios**
#CFE1F7 / #EFF1E1

**Lijiang Tower**
#D6EBF5 / #E8DDEC

**Nepal**
#E5EEFE / #EEE2EE

**Oasis**
#F6E2E8 / #FFF1E3

**Comment by RobThePM** [comment]
I can take a look at this later tonight when I get home. :)

**Comment by RobThePM** [comment]
colors look great. maybe in a future verzion we could add some sort of light pattern/design.

i saw something above about maybe taking screenshots in game. did you still need someone to do that? (i.e. me)

**Comment by cheshire137** [comment]
> taking screenshots in game. did you still need someone to do that? 

We do! Bust out your Print Screen key. 😀

**Comment by RobThePM** [comment]
alright, ETA later tonight or tomorrow

**Comment by cheshire137** [comment]
Thanks @smbriones! I'll get those hex colors hooked up in the app.
