### ISSUE TITLE
Change the color of the map select text

### ISSUE THREAD

**Issue by RobThePM** [cheshire137/overwatch-team-comps#83]
When I click on the map select drop down menu, both the text and the background are white.

**Comment by cheshire137** [comment]
While I don't see the white text and background that Rob's talking about, I'm testing in Chrome on macOS and I think Rob's on Windows. I think this is a side effect of using a normal HTML `<select>` element for choosing maps. I also dislike that the font size in the drop-down is as large as the font size of the selected map name. We could get around this and fix the color issue at the same time by moving off of the native select element to a custom `<div>` menu, or we could try to overload the styling of the native `<select>` but that can be hard to do consistently across browsers.

**Comment by RobThePM** [comment]
I'm testing in Chrome on Windows. I can also test in other browsers if needed.

**Comment by celluj34** [comment]
Works fine for me in FFx53 on Windows 7.

**Comment by RobThePM** [comment]
Here's a screenshot of my messed up screen. :)

[![https://gyazo.com/d502f1cc509a889b2ef1d42efe217498](https://i.gyazo.com/d502f1cc509a889b2ef1d42efe217498.gif)](https://gyazo.com/d502f1cc509a889b2ef1d42efe217498)

![white background and white text maps](https://cloud.githubusercontent.com/assets/26153402/26615551/865172a6-457c-11e7-95da-1557f89dda07.png)

**Comment by RobThePM** [comment]
I also tried going to https://overwatch-team-comps.herokuapp.com/ in Internet Explorer and I just see a white screen. :)
