### ISSUE TITLE
Test the product before version 1 go live

### ISSUE THREAD

**Issue by RobThePM** [cheshire137/overwatch-team-comps#95]
This is really just a reminder for me to perform ongoing testing of the product before go live. I'll create separate issues for each individual bug, etc.

I'm also happy to delete this issue if it doesn't really belong here as an issue.

**Comment by RobThePM** [comment]
@cheshire137 should i continue to test now or would it be better to wait until more of the features have been implemented? (e.g. in order to avoid me testing something that is already in the works to be fixed/implemented)

**Comment by cheshire137** [comment]
I think it's fine to test now on Heroku, the major features are all there.

**Comment by RobThePM** [comment]
i think we're all doing ongoing testing. im going to close to de-clutter the issues list.
