### ISSUE TITLE
Blank white screen, no JS errors

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#96]
@RobThePM went back to the app in his same Windows Chrome browser and got a blank screen instead. He opened the JavaScript console but didn't see any errors.

I thought maybe it could be because of using http instead of https, but the page still loads for me like that. That probably only affects OAuth sign in.

**Comment by cheshire137** [comment]
I was able to reproduce this locally! While signed out on the About page, I went a route /user that I shouldn't be able to access while signed out. It took me back to / but as a blank page instead of the team comp form. I'll get this fixed.

**Comment by RobThePM** [comment]
Awesome, thanks!

**Comment by RobThePM** [comment]
I can confirm that it works!

Note that I'm signed in, but it shows "Sign in with Battle.net" in the upper right. I'll report as a separate issue. Thanks!

![image](https://cloud.githubusercontent.com/assets/26153402/24326235/5f488a3a-1167-11e7-877c-2b9579393d69.png)

![image](https://cloud.githubusercontent.com/assets/26153402/24326224/16ea8752-1167-11e7-98c0-97687dcaf57c.png)
